// <auto-generated />
using System;
using Dilemma.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Dilemma.DAL.Migrations
{
    [DbContext(typeof(DilemmaDbContext))]
    [Migration("20210609112822_AddRealDilemmaData")]
    partial class AddRealDilemmaData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Dilemma.DAL.Models.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Dilemma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dilemmas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c402251d-10a7-402d-afb2-295cf7046fdc"),
                            Text = "Знакомая вам пара сознательно отказывается заводить детей и выбирает карьеру и жизнь в свое удовольствие. Как вы к этому отнесетесь?"
                        },
                        new
                        {
                            Id = new Guid("f85ee938-d711-49d4-a6a1-8de2231e26dd"),
                            Text = "Пара расстается после известия о беременности. Из-за этого девушка решает сделать аборт. Какова будет ваша реакция на поступок?"
                        },
                        new
                        {
                            Id = new Guid("94b9bb67-0cf1-47dc-a92e-746f44d7252f"),
                            Text = "Пара расстается после известия о беременности. Из-за этого девушка решает сделать аборт. Какова будет ваша реакция на поступок?"
                        },
                        new
                        {
                            Id = new Guid("6582873e-3515-4388-9aec-79091acd0094"),
                            Text = "Вы увидели синяки у вашей соседки. Каковы будут ваши действия?"
                        },
                        new
                        {
                            Id = new Guid("9f90a090-2a70-45e3-b45b-ce9ceda9f616"),
                            Text = "Ваш приятель рассказал, что наконец-то нашёл занятие себе по душе - стал видеоблоггером. Одобрите ли вы такой выбор?"
                        },
                        new
                        {
                            Id = new Guid("152ad382-fcef-4a44-82aa-4476798881dd"),
                            Text = "Вы узнаёте, что ваш однокурсник получил выгодное предложение о работе за границей и собирается переехать, а в перспективе - получить гражданство. Поддержите ли вы его решение?"
                        },
                        new
                        {
                            Id = new Guid("bf269761-6bfb-4c77-91c8-e5a8e390c746"),
                            Text = "Вы узнаёте из новостей, что известный стенд-ап комик был оштрафован за неуместную шутку, оскорбляющую чувства верующих людей. Каково будет ваше отношение к этой ситуации?"
                        },
                        new
                        {
                            Id = new Guid("a7cd9705-26d2-401b-8131-24618b6143e2"),
                            Text = "Встретившись со своим приятелем, вы узнаёте, что его совершеннолетний сын решил совершить трансгендерный переход, приятель поддерживает это решение. Как вы отнесётесь к данной ситуации?"
                        },
                        new
                        {
                            Id = new Guid("6956ccc6-6d27-49f7-9ed3-39044ecfee6a"),
                            Text = "Вы - врач-акушер, принимаете роды. Женщина находится в критическом состоянии, но ее еще можно спасти, однако ребенок умрет. Если вы решите спасти ребенка, то умрет женщина. Какой вариант вы выберите?"
                        },
                        new
                        {
                            Id = new Guid("65ed6b61-70de-400a-aa01-23c4b11d8e96"),
                            Text = "Вы являетесь начальником отдела в компании. Сверху поступает требование сократить одного сотрудника, так как компания столкнулась с финансовыми трудностями. В вашем отделе, помимо вас, работает два человека. Первый сотрудник - женщина, которая, по объективным показателям эффективности работает хуже, однако вам известно, что у нее есть мать-инвалид, за которым она ухаживает и несовершеннолетний ребенок, которого она воспитывает одна. Второй сотрудник - мужчина, который по показателям эффективности значительно превосходит первого сотрудника. Кого решите уволить?"
                        },
                        new
                        {
                            Id = new Guid("33bffdc8-05af-4dc1-a16f-75fa8c72793a"),
                            Text = "За обучение в ВУЗе платят ваши родители. Вы знаете, что это сильно бьет по их бюджету.  В текущем семестре у вас есть возможность получить большую скидку на обучение, если вы сдадите экзамен на 5. Перед экзаменом профессор сообщил, что есть возможность получить 5 за экзамен, если вы сдадите человека, который списывает, после чего вы не будете деанонимизированы. В ходе экзамена, вы чувствуете, что пятерку не получите, однако вы видите, как ваш хороший друг списывает."
                        });
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DilemmaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DilemmaId");

                    b.ToTable("Solutions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1106eb04-c329-4269-aaf1-1a23597f0ad4"),
                            DilemmaId = new Guid("c402251d-10a7-402d-afb2-295cf7046fdc"),
                            Image = "dilemma_1_solution_1.jpeg",
                            Rate = 0.40000000000000002,
                            Text = "Они взрослые люди и должны сами решать, как им жить. Поддержу их выбор внезависимости от своих предпочтений."
                        },
                        new
                        {
                            Id = new Guid("980f4abf-acce-4057-ad3d-49e668b94838"),
                            DilemmaId = new Guid("c402251d-10a7-402d-afb2-295cf7046fdc"),
                            Image = "dilemma_1_solution_2.jpeg",
                            Rate = -0.40000000000000002,
                            Text = "Глупое и бездумное решение. Буду пытаться доказать им, что их выбор не верен."
                        },
                        new
                        {
                            Id = new Guid("6ff67647-49cc-4098-9d58-a6cd3d4c6fcf"),
                            DilemmaId = new Guid("f85ee938-d711-49d4-a6a1-8de2231e26dd"),
                            Image = "dilemma_2_solution_1.jpeg",
                            Rate = 0.5,
                            Text = "Аборт делать ни в коем случае нельзя ведь это ребенок. А вырастить можно и самой. Родные помогут."
                        },
                        new
                        {
                            Id = new Guid("c6bc174d-49ff-4a19-8444-08fd7e0cdc70"),
                            DilemmaId = new Guid("f85ee938-d711-49d4-a6a1-8de2231e26dd"),
                            Image = "dilemma_2_solution_2.jpeg",
                            Rate = -0.90000000000000002,
                            Text = "Девушка поступила, как ей казалось правильным. Мы не знаем всех причин и не может судить о ее поступке."
                        },
                        new
                        {
                            Id = new Guid("b02e022c-3c28-4556-a492-4cb48dc3e731"),
                            DilemmaId = new Guid("94b9bb67-0cf1-47dc-a92e-746f44d7252f"),
                            Image = "dilemma_3_solution_1.jpeg",
                            Rate = 0.80000000000000004,
                            Text = "Как и с любыми другими соседями. Их личная жизнь - это их дело."
                        },
                        new
                        {
                            Id = new Guid("90de8c66-0fc0-4f03-ad04-c4a38bc26524"),
                            DilemmaId = new Guid("94b9bb67-0cf1-47dc-a92e-746f44d7252f"),
                            Image = "dilemma_3_solution_2.jpeg",
                            Rate = -0.90000000000000002,
                            Text = "Буду избегать их и показывать свое неодобрение, потому что это не правильно. Постараюсь избежать всех контактов с ними."
                        },
                        new
                        {
                            Id = new Guid("95dc0a17-d1c1-454c-a198-d4cfa3210a84"),
                            DilemmaId = new Guid("6582873e-3515-4388-9aec-79091acd0094"),
                            Image = "dilemma_4_solution_1.jpeg",
                            Rate = 0.90000000000000002,
                            Text = "Не буду вмешиваться. Взрослые люди должны разбираться сами. Это не мое дело."
                        },
                        new
                        {
                            Id = new Guid("f562b4fc-0df5-46a4-bc87-8dc58c40d0ef"),
                            DilemmaId = new Guid("6582873e-3515-4388-9aec-79091acd0094"),
                            Image = "dilemma_4_solution_2.jpeg",
                            Rate = -0.40000000000000002,
                            Text = "Постараюсь поговорить с ней. Предложить помощь, если нужно. Помогу справиться со стрессом и страхом."
                        },
                        new
                        {
                            Id = new Guid("f470c0d5-ae07-4ed3-b2c4-8df3574176ba"),
                            DilemmaId = new Guid("9f90a090-2a70-45e3-b45b-ce9ceda9f616"),
                            Image = "dilemma_5_solution_1.jpeg",
                            Rate = 0.5,
                            Text = "Я поддержу приятеля, ведь главное - заниматься тем, что тебе нравится и получать удовольствие."
                        },
                        new
                        {
                            Id = new Guid("2343e27b-c648-4ed6-889f-0c79518dec55"),
                            DilemmaId = new Guid("9f90a090-2a70-45e3-b45b-ce9ceda9f616"),
                            Image = "dilemma_5_solution_2.jpeg",
                            Rate = -0.5,
                            Text = "Я посоветую приятелю заняться чем-нибудь более серьёзным и полезным для общества."
                        },
                        new
                        {
                            Id = new Guid("a1d867b0-1945-4e79-8675-4e6ca912c200"),
                            DilemmaId = new Guid("152ad382-fcef-4a44-82aa-4476798881dd"),
                            Image = "dilemma_6_solution_1.jpeg",
                            Rate = 0.5,
                            Text = "Конечно, ведь за границей у него открываются отличные возможности для саморазвития и карьерного роста."
                        },
                        new
                        {
                            Id = new Guid("b8dd2a6e-1636-4f6b-8394-046e5bd7ffcc"),
                            DilemmaId = new Guid("152ad382-fcef-4a44-82aa-4476798881dd"),
                            Image = "dilemma_6_solution_2.jpeg",
                            Rate = -0.5,
                            Text = "Не поддержу такое решение, ведь государство вложило огромные силы и средства в его обучение - как в школе, так на бюджетном месте университета. Теперь ему следует дать государству что-то взамен."
                        },
                        new
                        {
                            Id = new Guid("96500b2b-9e81-466f-b722-4d3370ed2e86"),
                            DilemmaId = new Guid("bf269761-6bfb-4c77-91c8-e5a8e390c746"),
                            Image = "dilemma_7_solution_1.jpeg",
                            Rate = 0.80000000000000004,
                            Text = "Существуют темы, на которые шутить нельзя, потому что они задевают чувства некоторых людей. Если в обществе есть запретные темы, их не стоит использовать для развлечения."
                        },
                        new
                        {
                            Id = new Guid("22e6fc6d-e8ce-4f44-9f96-1ba05b02a93c"),
                            DilemmaId = new Guid("bf269761-6bfb-4c77-91c8-e5a8e390c746"),
                            Image = "dilemma_7_solution_2.jpeg",
                            Rate = -0.29999999999999999,
                            Text = "Запретных тем нет - если человек хочет высмеять те или иные социокультурные аспекты, он имеет на это полное право. Те, кому это не нравится, могут не слушать."
                        },
                        new
                        {
                            Id = new Guid("21729881-ef78-4605-8b4a-d8919e47b3c4"),
                            DilemmaId = new Guid("a7cd9705-26d2-401b-8131-24618b6143e2"),
                            Image = "dilemma_8_solution_1.jpeg",
                            Rate = 0.80000000000000004,
                            Text = "Задумаюсь о том, что за подобные аморальные действия по отношению к своему ребёнку стоит лишать родительских прав."
                        },
                        new
                        {
                            Id = new Guid("7ccf98ab-e030-4f6a-8df5-26005c4be448"),
                            DilemmaId = new Guid("a7cd9705-26d2-401b-8131-24618b6143e2"),
                            Image = "dilemma_8_solution_2.jpeg",
                            Rate = -0.29999999999999999,
                            Text = "Порадуюсь о взаимопонимании и поддержке, существующих между между отцом и его ребёнком."
                        },
                        new
                        {
                            Id = new Guid("335c3917-2c0c-443f-94fc-daf3db63c554"),
                            DilemmaId = new Guid("6956ccc6-6d27-49f7-9ed3-39044ecfee6a"),
                            Image = "dilemma_9_solution_1.jpeg",
                            Rate = 0.80000000000000004,
                            Text = "Нужно спасти ребенка, так как он - будущая ячейка общества."
                        },
                        new
                        {
                            Id = new Guid("61d1e5d9-09c2-40ae-811d-e39f622b5341"),
                            DilemmaId = new Guid("6956ccc6-6d27-49f7-9ed3-39044ecfee6a"),
                            Image = "dilemma_9_solution_2.jpeg",
                            Rate = -0.90000000000000002,
                            Text = "Нужно спасти женщину, так как она уже является членом общества, у которого есть социальные связи, близкие люди. Общество получит большую пользу от ее спасения."
                        },
                        new
                        {
                            Id = new Guid("c08b86b1-2347-4097-8ffd-6cddc5984c49"),
                            DilemmaId = new Guid("65ed6b61-70de-400a-aa01-23c4b11d8e96"),
                            Image = "dilemma_10_solution_1.jpeg",
                            Rate = 0.80000000000000004,
                            Text = "Женщину, так как компания и так испытывает финансовые трудности. Компании непозволительно иметь неэффективного сотрудника."
                        },
                        new
                        {
                            Id = new Guid("95582cfb-c260-4ec2-bf61-6923e332d278"),
                            DilemmaId = new Guid("65ed6b61-70de-400a-aa01-23c4b11d8e96"),
                            Image = "dilemma_10_solution_2.jpeg",
                            Rate = -0.29999999999999999,
                            Text = "Мужчину. У него нет серьезных проблем в жизни, и с поиском работы тоже не будет."
                        },
                        new
                        {
                            Id = new Guid("a9e4c772-a9f2-49dd-8852-83232b6b1b13"),
                            DilemmaId = new Guid("33bffdc8-05af-4dc1-a16f-75fa8c72793a"),
                            Image = "dilemma_11_solution_1.jpeg",
                            Rate = 0.59999999999999998,
                            Text = "Как бы ни была важна дружба, скидка очень сильно нужна. Тем более друг об этом не узнает."
                        },
                        new
                        {
                            Id = new Guid("d024b44e-3bcb-40d7-95db-7e73d6ef9258"),
                            DilemmaId = new Guid("33bffdc8-05af-4dc1-a16f-75fa8c72793a"),
                            Image = "dilemma_11_solution_2.jpeg",
                            Rate = -0.80000000000000004,
                            Text = "Искренняя и честная дружба будет важнее."
                        });
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Statistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Answer", b =>
                {
                    b.HasOne("Dilemma.DAL.Models.Solution", "Solution")
                        .WithMany("Answers")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solution");
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Solution", b =>
                {
                    b.HasOne("Dilemma.DAL.Models.Dilemma", "Dilemma")
                        .WithMany("Solutions")
                        .HasForeignKey("DilemmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dilemma");
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Dilemma", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Dilemma.DAL.Models.Solution", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
